version: "3"
services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - "5542:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: development
      POSTGRES_DB: nestjs_ecommerce
      PGDATA: /var/lib/postgres