module.exports = {
  type: 'postgres',
  host: process.env.PG_DB_HOST,
  port: Number(process.env.PG_DB_PORT),
  username: process.env.PG_DB_USER,
  password: String(process.env.PG_DB_PASSWORD),
  database: process.env.PG_DB_NAME,
  entities: [__dirname + '/../modules/**/*.entity.{js,ts}'],
  autoLoadEntities: false,
  migrationsTableName: 'migration',
  migrations: ['src/database/migrations/**/*.ts'],
  subscribers: ['src/database/subscribers/**/*.ts'],
  factories: ['src/database/factories/**/*{.ts,.js}'],
  seeds: ['src/database/seeds/**/*{.ts,.js}'],
  synchronize: false,
  cli: {
    migrationsDir: 'src/database/migrations',
    subscribersDir: 'src/database/subscribers',
  },
  logging: true,
  logger: 'advanced-console',
};
